Simplify rendering pipeline, reduce gpu memory usage, remove duplicated data
grovesNL/glyphon pull request #86
Opened 2024-03-12 16:47 UTC by PPakalns

2024-03-12 21:51 UTC, PPakalns commented
Didn't know that, learned something new :)

2024-03-30 14:21 UTC, hecrj commented
I tested these changes together with #90, #91, and #92 in a relatively big app and I see a noticeable speedup on my M1 (from 2ms frame time to 1.7ms). I guess it's expected since the `prepare` loop does quite less. GPU usage seems unaffected.

2024-03-30 14:22 UTC, hecrj requested changes

2024-04-27 19:05 UTC, PPakalns commented on src/text_render.rs
> +    gylphs_to_render: u32,
Fixed

2024-05-27 01:22 UTC, grovesNL commented
I just rebased this onto `main`. Let's go ahead with this for the CPU time improvements.

It's possible it could regress GPU time some specific older hardware that doesn't handle small instances well, but most modern hardware should be ok with this based on what I can tell. e.g., it's confirmed that AMD has optimizations for small instances now instead of doing the slow thing that used to happen.

If we see a noticeable performance problem with any hardware then we can always special case certain vendors and expand the vertices out in those cases.

2024-05-27 01:22 UTC, merged